// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class DbQueryStatus_getMessage_3d85e9375f_Test {

    private DbQueryStatus dbQueryStatus;

    @BeforeEach
    public void setup() {
        dbQueryStatus = new DbQueryStatus("Test message", DbQueryExecResult.QUERY_OK);
    }

    @Test
    public void testGetMessage_Success() {
        String expectedMessage = "Test message";
        String actualMessage = dbQueryStatus.getMessage();
        assertEquals(expectedMessage, actualMessage);
    }

    @Test
    public void testGetMessage_Failure() {
        String unexpectedMessage = "Unexpected message";
        String actualMessage = dbQueryStatus.getMessage();
        assertNotEquals(unexpectedMessage, actualMessage);
    }
}
