// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class DbQueryStatus_setMessage_41fefe61bb_Test {

    private DbQueryStatus dbQueryStatus;

    @BeforeEach
    public void setUp() {
        dbQueryStatus = new DbQueryStatus();
    }

    @Test
    public void testSetMessage_Success() {
        String expectedMessage = "Test message";
        dbQueryStatus.setMessage(expectedMessage);
        assertEquals(expectedMessage, dbQueryStatus.getMessage());
    }

    @Test
    public void testSetMessage_Null() {
        dbQueryStatus.setMessage(null);
        assertEquals(null, dbQueryStatus.getMessage());
    }

    @Test
    public void testSetMessage_EmptyString() {
        dbQueryStatus.setMessage("");
        assertEquals("", dbQueryStatus.getMessage());
    }
}
