// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class DbQueryStatus_setData_12e936db44_Test {

    @Test
    public void testSetDataWithNonNullObject() {
        DbQueryStatus dbQueryStatus = new DbQueryStatus();
        String expectedData = "Test data";
        dbQueryStatus.setData(expectedData);

        Assertions.assertEquals(expectedData, dbQueryStatus.getData(), "The data should be set correctly");
    }

    @Test
    public void testSetDataWithNullObject() {
        DbQueryStatus dbQueryStatus = new DbQueryStatus();
        dbQueryStatus.setData(null);

        Assertions.assertNull(dbQueryStatus.getData(), "The data should be null");
    }
}
