// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class DbQueryStatus_setdbQueryExecResult_8c71b1edb0_Test {

    private DbQueryStatus dbQueryStatus;
    private DbQueryExecResult mockDbQueryExecResult;

    @BeforeEach
    public void setUp() {
        dbQueryStatus = new DbQueryStatus();
        mockDbQueryExecResult = Mockito.mock(DbQueryExecResult.class);
    }

    @Test
    public void testSetDbQueryExecResult_Success() {
        dbQueryStatus.setdbQueryExecResult(mockDbQueryExecResult);
        assertEquals(mockDbQueryExecResult, dbQueryStatus.getDbQueryExecResult());
    }

    @Test
    public void testSetDbQueryExecResult_Null() {
        dbQueryStatus.setdbQueryExecResult(null);
        assertEquals(null, dbQueryStatus.getDbQueryExecResult());
    }
}
