// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class DbQueryStatus_DbQueryStatus_b51a08dbfb_Test {

    @Mock
    DbQueryExecResult dbQueryExecResult;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDbQueryStatus_Success() {
        String message = "Success";
        DbQueryStatus dbQueryStatus = new DbQueryStatus(message, dbQueryExecResult);

        assertEquals(message, dbQueryStatus.getMessage());
        assertEquals(dbQueryExecResult, dbQueryStatus.getdbQueryExecResult());
    }

    @Test
    public void testDbQueryStatus_Failure() {
        String message = "Failure";
        DbQueryStatus dbQueryStatus = new DbQueryStatus(message, dbQueryExecResult);

        assertEquals(message, dbQueryStatus.getMessage());
        assertEquals(dbQueryExecResult, dbQueryStatus.getdbQueryExecResult());
    }
}
