// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class DbQueryStatus_getData_9a28503eab_Test {

    private DbQueryStatus dbQueryStatus;

    @BeforeEach
    public void setup() {
        dbQueryStatus = new DbQueryStatus();
    }

    @Test
    public void testGetData_WhenDataIsNull() {
        assertNull(dbQueryStatus.getData(), "Data should be null");
    }

    @Test
    public void testGetData_WhenDataIsNotNull() {
        String expectedData = "Test Data";
        dbQueryStatus.setData(expectedData);
        assertEquals(expectedData, dbQueryStatus.getData(), "Data should match the expected value");
    }
}
