// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class ProfileController_ProfileController_a3e6d3901c_Test {

    private ProfileDriverImpl profileDriver;
    private PlaylistDriverImpl playlistDriver;
    private ProfileController profileController;

    @BeforeEach
    public void setup() {
        profileDriver = mock(ProfileDriverImpl.class);
        playlistDriver = mock(PlaylistDriverImpl.class);
        profileController = new ProfileController(profileDriver, playlistDriver);
    }

    @Test
    public void testProfileControllerConstructor() {
        // Test for successful object creation
        ProfileController testController = new ProfileController(profileDriver, playlistDriver);
        assertEquals(testController.profileDriver, profileDriver);
        assertEquals(testController.playlistDriver, playlistDriver);
    }

    @Test
    public void testProfileControllerConstructor_NullProfileDriver() {
        // Test for null profileDriver
        Exception exception = null;
        try {
            new ProfileController(null, playlistDriver);
        } catch (NullPointerException e) {
            exception = e;
        }
        assertEquals(NullPointerException.class, exception.getClass());
    }

    @Test
    public void testProfileControllerConstructor_NullPlaylistDriver() {
        // Test for null playlistDriver
        Exception exception = null;
        try {
            new ProfileController(profileDriver, null);
        } catch (NullPointerException e) {
            exception = e;
        }
        assertEquals(NullPointerException.class, exception.getClass());
    }
}
