// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.neo4j.driver.v1.*;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class ProfileDriverImpl_InitProfileDb_661ce5d9f1_Test {

    private Driver driver;
    private Session session;
    private Transaction transaction;

    @BeforeEach
    public void setup() {
        driver = mock(Driver.class);
        session = mock(Session.class);
        transaction = mock(Transaction.class);

        when(driver.session()).thenReturn(session);
        when(session.beginTransaction()).thenReturn(transaction);
        ProfileMicroserviceApplication.driver = driver;
    }

    @Test
    public void testInitProfileDb_Success() {
        ProfileDriverImpl.InitProfileDb();

        verify(session, times(1)).beginTransaction();
        verify(transaction, times(3)).run(anyString());
        verify(transaction, times(1)).success();
        verify(session, times(1)).close();
    }

    @Test
    public void testInitProfileDb_Failure_ThrowsException() {
        when(session.beginTransaction()).thenThrow(new RuntimeException("Transaction error"));

        assertThrows(RuntimeException.class, () -> ProfileDriverImpl.InitProfileDb());

        verify(session, times(1)).beginTransaction();
        verify(transaction, times(0)).run(anyString());
        verify(transaction, times(0)).success();
        verify(session, times(1)).close();
    }
}
