// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.neo4j.driver.v1.Driver;
import org.neo4j.driver.v1.Session;
import org.neo4j.driver.v1.Transaction;

public class ProfileDriverImpl_createUserProfile_715f4d656e_Test {

    private Driver driver;
    private Session session;
    private Transaction transaction;

    @BeforeEach
    public void setup() {
        driver = mock(Driver.class);
        session = mock(Session.class);
        transaction = mock(Transaction.class);

        when(driver.session()).thenReturn(session);
        when(session.beginTransaction()).thenReturn(transaction);
    }

    @Test
    public void testCreateUserProfile_Success() {
        ProfileDriverImpl profileDriver = new ProfileDriverImpl(driver);

        DbQueryStatus status = profileDriver.createUserProfile("testUser", "testFullName", "testPassword");

        assertEquals(DbQueryExecResult.QUERY_OK, status.getdbQueryExecResult());
    }

    @Test
    public void testCreateUserProfile_Failure_NullParameters() {
        ProfileDriverImpl profileDriver = new ProfileDriverImpl(driver);

        DbQueryStatus status = profileDriver.createUserProfile(null, null, null);

        assertEquals(DbQueryExecResult.QUERY_ERROR_GENERIC, status.getdbQueryExecResult());
    }

    @Test
    public void testCreateUserProfile_Failure_ExceptionThrown() {
        when(session.beginTransaction()).thenThrow(new RuntimeException());

        ProfileDriverImpl profileDriver = new ProfileDriverImpl(driver);

        DbQueryStatus status = profileDriver.createUserProfile("testUser", "testFullName", "testPassword");

        assertEquals(DbQueryExecResult.QUERY_ERROR_GENERIC, status.getdbQueryExecResult());
    }
}
