// Test generated by RoostGPT for test Spotify-Test using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.util.Assert;

import java.util.HashMap;
import java.util.Map;

public class Utils_setResponseStatus_d74fe01b5e_Test {

    @Test
    public void testSetResponseStatus_QUERY_OK() {
        Map<String, Object> response = new HashMap<>();
        Object data = new Object();
        Utils.setResponseStatus(response, DbQueryExecResult.QUERY_OK, data);

        Assert.isTrue(response.get("status") == HttpStatus.OK, "Status should be OK");
        Assert.isTrue(response.get("data") == data, "Data should be equal to input data");
    }

    @Test
    public void testSetResponseStatus_QUERY_ERROR_NOT_FOUND() {
        Map<String, Object> response = new HashMap<>();
        Utils.setResponseStatus(response, DbQueryExecResult.QUERY_ERROR_NOT_FOUND, null);

        Assert.isTrue(response.get("status") == HttpStatus.NOT_FOUND, "Status should be NOT_FOUND");
        Assert.isNull(response.get("data"), "Data should be null");
    }

    @Test
    public void testSetResponseStatus_QUERY_ERROR_GENERIC() {
        Map<String, Object> response = new HashMap<>();
        Utils.setResponseStatus(response, DbQueryExecResult.QUERY_ERROR_GENERIC, null);

        Assert.isTrue(response.get("status") == HttpStatus.INTERNAL_SERVER_ERROR, "Status should be INTERNAL_SERVER_ERROR");
        Assert.isNull(response.get("data"), "Data should be null");
    }
}
